$(document).ready(function(e){
	$("#login").click(function(){
		location.href="login_btn";
	});
	$("#register").click(function(){
		location.href="register";
	});
	$("#main").click(function(){
		location.href="main";
	});		
});
